development:  
  adapter: postgresql
  encoding: unicode
  database: myapp2
  pool: 5
  username: postgres
  password:

test:  
  adapter: postgresql
  encoding: unicode
  database: myapp1
  pool: 5
  username: postgres
  password:

# production:
#   <<: *default
#   database: db/production.sqlite3
